export type ResultCategory = 'dismissed' | 'not-guilty' | 'reduced-charges'

export interface CaseResult {
  id: number
  title: string
  summary: string
  category: ResultCategory
}

export const CASE_RESULTS: CaseResult[] = [
  { id: 1, title: 'Drug DUI with Injuries Trial', summary: 'Our client faced charges for driving under the influence of drugs following a multi-car accident. Despite alleged admissions of prior drug use and claims of reckless driving, our firm secured a Not Guilty verdict on all counts after a full bench trial.', category: 'not-guilty' },
  { id: 2, title: 'Accident Resulting in Death Trial', summary: 'A CDL driver was charged in a fatal collision. Our attorneys rejected plea deals, took the case to trial, and utilized expert video evidence to prove our client\'s innocence. The judge returned a finding of not guilty for all charges.', category: 'not-guilty' },
  { id: 3, title: 'Criminal Trespass to State Land Trial', summary: 'While on felony probation, our client was accused of trespassing. Even with officer testimony and a "No Trespassing" sign present, we proceeded to trial and successfully had all charges thrown out without our client ever needing to testify.', category: 'dismissed' },
  { id: 4, title: 'DUI Trial and Motion', summary: 'Facing a second DUI and a mandatory three-year license suspension, our client turned to us for help. We argued the police lacked a legal basis for the initial stop. The judge agreed, the suspension was vacated, and the DUI was won.', category: 'dismissed' },
  { id: 5, title: 'Felony Theft Trial', summary: 'A bank teller was charged with multiple felonies for allegedly fraudulent transactions caught on video. Our experienced defense counsel effectively challenged the prosecution\'s narrative, leading to a complete victory and acquittal for our client.', category: 'not-guilty' },
  { id: 6, title: 'Unlawful Use of Weapon (UUW) Trial', summary: 'During a traffic stop, police claimed our client reached for a loaded handgun. We filed a motion to quash the arrest and suppress the evidence rather than accepting a plea. The motion was granted, and all charges were dismissed.', category: 'dismissed' },
  { id: 7, title: 'Leaving Scene of Accident Trial', summary: 'Despite testimony that our client confessed to the crime, our legal team successfully objected to the admission of that confession. With the evidence excluded, our client was found not guilty and immediately released from custody.', category: 'not-guilty' },
  { id: 8, title: 'Fatigued Driving Accident Trial', summary: 'Our client was accused of falling asleep before hitting an IDOT truck. By personally visiting the scene and demonstrating that our client was not responsible for the collision, we convinced the judge to issue a not guilty ruling on all tickets.', category: 'not-guilty' },
  { id: 9, title: 'Possession with Intent to Deliver Motion', summary: 'Facing a year in jail after a confession, our team challenged the legality of the arrest location. The judge agreed that the officers\' actions were improper, suppressed the evidence, and dismissed all drug charges against our client.', category: 'dismissed' },
  { id: 10, title: 'Mob Action & Disorderly Conduct Trial', summary: 'Offered a conviction and community service, our client chose to fight. Following a rigorous cross-examination of the complaining witness, the court found our client not guilty on every count, preserving their clean record.', category: 'not-guilty' },
  { id: 11, title: 'Felony DUI & Revoked License Motion', summary: 'Facing five years in prison for a felony DUI, our client\'s future was in jeopardy. We filed a Motion to Quash Arrest, which the judge granted. Consequently, every criminal charge in the case was completely dismissed.', category: 'dismissed' },
  { id: 12, title: 'Battery Trial', summary: 'Four witnesses, including an off-duty officer, testified against our client. Through strategic defense and despite having no witnesses of our own, we secured a not guilty verdict on all counts at the conclusion of the trial.', category: 'not-guilty' },
  { id: 13, title: 'Resisting & Obstructing Arrest Trial', summary: 'Police alleged they saw our client swallow drugs during an arrest, and a confession followed. Through extensive research and a strong trial defense, we overcame the prosecution\'s evidence to secure not guilty verdicts for our client.', category: 'not-guilty' },
  { id: 14, title: 'Felony Theft Jury Trial', summary: 'A store manager accused of significant theft chose to fight for their reputation. We convinced the jury that the prosecution had not met its burden, resulting in a not guilty verdict on all counts instead of a reduced charge.', category: 'not-guilty' },
  { id: 15, title: 'DUI Trial', summary: 'Our client was accused of nearly striking pedestrians during the Chicago Marathon and then attempting to punch an officer. Despite this testimony, our attorney\'s trial performance resulted in a finding of not guilty on the DUI charge.', category: 'not-guilty' },
  { id: 16, title: 'Reckless Driving & High Speeding Trial', summary: 'When an officer tried to use personal notes not disclosed in discovery, our attorney quickly objected. The judge suppressed the information, and due to this rapid legal maneuvering, our client was found not guilty of the charges.', category: 'not-guilty' },
  { id: 17, title: 'Battery & Resisting Police Trial', summary: 'Accused of pushing an officer and resisting arrest, our client took the matter to a bench trial. Our defense successfully challenged the state\'s version of events, leading to a dismissal of charges and a not guilty finding.', category: 'not-guilty' },
  { id: 18, title: 'Felony Public Indecency Trial', summary: 'A client facing lifetime sex offender registration benefited from our attorney\'s discovery of a legal loophole. Faced with a likely loss at trial, the prosecutor agreed to reduce the felony to a misdemeanor with no registration required.', category: 'reduced-charges' },
  { id: 19, title: 'Battery Trial', summary: 'Even after being positively identified by an eyewitness in court for a violent battery charge, our client walked away free. We won the trial by undermining the identification, resulting in a full acquittal on all charges.', category: 'not-guilty' },
  { id: 20, title: 'Violation of Order of Protection Motion', summary: 'Using extensive research from a related divorce proceeding, our legal team filed a motion to dismiss the violation charges. The court granted our motion, ending the prosecution and dismissing all charges against our client.', category: 'dismissed' },
  { id: 21, title: 'DUI Trial', summary: 'Our client admitted to drinking and failed field tests. However, through precise cross-examination, we exposed inconsistencies in the police reports. The judge dismissed the entire case without our client needing to take the stand.', category: 'dismissed' },
  { id: 22, title: 'Battery Trial', summary: 'Accused of attacking a repossession agent, our client followed our advice to go to trial. A strong cross-examination revealed flaws in the state\'s case, leading to a full acquittal for our client on all battery allegations.', category: 'not-guilty' },
  { id: 23, title: 'Criminal Trespass & Disorderly Conduct Trial', summary: 'Despite being found in a yard after a previous arrest at the same location, our client was acquitted. Our hard work and preparation at trial ensured that the allegations did not result in a conviction.', category: 'not-guilty' },
  { id: 24, title: 'Predatory Criminal Sexual Assault Motion', summary: 'Facing years in prison for a probation violation, we moved to vacate a prior related conviction. Our extensive legal research was successful, ultimately resulting in a full dismissal of the serious charges against our client.', category: 'dismissed' },
  { id: 25, title: 'Battery Bench Trial', summary: 'A train conductor alleged our client committed battery with a bicycle. Our attorney presented a successful defense during the bench trial, resulting in a win and the protection of our client\'s criminal record.', category: 'not-guilty' },
  { id: 26, title: 'Theft Trial', summary: 'Our client was found with a truck full of stolen, GPS-tracked equipment. Despite the evidence, we successfully argued for a directed finding, meaning the judge ruled in our favor on all counts before the defense even started.', category: 'not-guilty' },
  { id: 27, title: 'Criminal Trespass to Residence', summary: 'Accused of squatting without a title to the property, our client faced criminal charges. The judge agreed with our specific legal arguments regarding property rights and occupancy, leading to a not guilty verdict.', category: 'not-guilty' },
  { id: 28, title: 'Self-Defense Battery Trial', summary: 'Rejecting a deal for a conviction, our client opted for a trial. We successfully asserted that our client\'s actions were legally justified as self-defense. The judge agreed and dismissed all battery charges.', category: 'dismissed' },
  { id: 29, title: 'Battery Bench Trial', summary: 'Despite four witnesses testifying to our client\'s guilt, our cross-examination changed the outcome. The judge determined our client was the only truthful party involved and issued a finding of not guilty.', category: 'not-guilty' },
  { id: 30, title: 'Unlawful Use of Weapon Bench Trial', summary: 'Our client was arrested for a gun found in a backpack. We argued that the backpack served as a legally "closed container" under the law. The judge agreed with our interpretation and found our client not guilty.', category: 'not-guilty' },
  { id: 31, title: 'Felony Revoked License Motion', summary: 'We identified a technicality regarding a license issued by another state to challenge a felony charge. Our legal team convinced the prosecutor to dismiss the case entirely before the motion was even argued in court.', category: 'dismissed' },
  { id: 32, title: 'DUI Motions and Bench Trial', summary: 'Our client failed a breathalyzer and was recorded on video. We successfully moved to suppress the evidence. At the subsequent trial, the judge ruled there was insufficient remaining evidence to support a conviction.', category: 'not-guilty' },
  { id: 33, title: 'DUI Motion', summary: 'After an improper police stop based on a faulty solicitation suspicion, our client was charged with DUI. We filed a motion to rescind the license suspension, which the judge granted, leading the state to dismiss all charges.', category: 'dismissed' },
  { id: 34, title: 'Felony Cannabis Possession Motion', summary: 'Police entered a home without a warrant based on an informant\'s tip. We filed a Motion to Suppress and Quash Arrest, arguing the search was unconstitutional. We won the motion, and the case was won.', category: 'dismissed' },
  { id: 35, title: 'Public Indecency', summary: 'A victim identified our client in a photo lineup and testified at trial. However, our attorney undermined that testimony and presented a solid alibi. The judge found our client not guilty of the new charges.', category: 'not-guilty' },
  { id: 36, title: 'Suspended Driver\'s License Motion', summary: 'Our attorney argued that the statute used for the charge required the incident to occur on a public road. The judge agreed with our legal interpretation of the location and dismissed the entire case.', category: 'dismissed' },
  { id: 37, title: 'Battery Bench Trial', summary: 'When our client faced battery allegations involving a co-worker, their career was on the line. Despite witness testimony, our defense successfully challenged the evidence, leading the Judge to find our client not guilty of all charges.', category: 'not-guilty' },
  { id: 38, title: 'Sexual Assault Bench Trial', summary: 'Even with digital evidence presented by the prosecution, our experienced attorneys leveraged a strategic defense. We convinced the Judge of the legal insufficiency of the state\'s case, resulting in a full acquittal for our client.', category: 'not-guilty' },
  { id: 39, title: 'DUI Motion', summary: 'Our legal team successfully filed a motion to dismiss after identifying a lack of probable cause for the initial arrest. By challenging the officer\'s legal basis, we secured a total dismissal of the DUI charges.', category: 'dismissed' },
  { id: 40, title: 'Aggravated Unlawful Use of Weapon Motion', summary: 'After a firearm was discovered in our client\'s vehicle, we filed a Motion to Quash Arrest. The Judge agreed that the police lacked sufficient cause for the traffic stop, leading to the suppression of evidence and a dismissal.', category: 'dismissed' },
  { id: 41, title: 'Aggravated Assault with a Deadly Weapon', summary: 'Despite multiple witnesses and a complex set of facts, our trial team effectively argued the nuances of the law. We successfully convinced the court to find our client not guilty of all aggravated assault charges.', category: 'not-guilty' },
]
